#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

panel_memory > "$PANEL_FIFO" &
panel_clock > "$PANEL_FIFO" &
panel_weather > "$PANEL_FIFO" &

bspc control --subscribe > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | panel_bar | bar -g 1920x15 -f '-*-GohuFontMod11-*-*-*-*-*-*-*-*-*-*-*-*' -p &
wait
