#! /bin/sh

bspc monitor -d I II II IV

#Padding on top
bspc config top_padding 14

# Visual options
bspc config split_ratio         0.50
bspc config border_width        2
bspc config window_gap          12
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#605655"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05

# Rules
bspc rule -a Thunar floating=on
bspc rule -a VirtualBox desktop=^2
bspc rule -a feh floating=on manage=off

panel &
