#! /bin/sh

FIRST_DESK_MAIN=i
REMAINING_DESKS_MAIN="ii iii iv v vi vii viii ix x"
FIRST_DESK_SECONDARY=I
REMAINING_DESKS_SECONDARY="II III IV V VI VII VIII IX X"

bspc desktop Desktop01 -n $FIRST_DESK_MAIN
bspc monitor -a $REMAINING_DESKS_MAIN

bspc rule -a Gimp -d Eight --floating

bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          4 
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Thunar --floating
bspc rule -a Deluge --floating
bspc rule -a feh --floating

panel &
#/home/michael/scripts/status_bar "#d6c3b6" "#181512" "-*-nu-*-*-*-*-*-*-*-*-*-*-*-*" &
