#! /bin/sh

FIRST_DESK=I
REMAINING_DESKS="II III IV V"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

bspc rule -a Gimp -d Eight --floating

bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          8 
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Thunar --floating
bspc rule -a Deluge --floating
bspc rule -a feh --floating

panel &
